GrmDigitalTask/Models/ErrorViewModel.cs
using System;

namespace GrmDigitalTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GrmDigitalTask/ViewModels/GrmTaskDodajVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GrmDigitalTask.ViewModels
{
    public class GrmTaskDodajVM
    {
        
        public int ID1 { get; set; }
        public int ID2 { get; set; }
        public List<SelectListItem> GrmTaskList1 { get; set; }
        public List<SelectListItem> GrmTaskList2 { get; set; }
        
        [Required(ErrorMessage = "Unesite broj.")]
        public int Prvi { get; set; }
        
        [Required]
        public int Drugi { get; set; }
        
    }
}

GrmDigitalTask/ViewModels/GrmTaskPrikazVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GrmDigitalTask.ViewModels
{
    public class GrmTaskPrikazVM
    {
        public int ID { get; set; }
        public int Position { get; set; }
        public string Name { get; set; }
        public int Score { get; set; }
    }
}

GrmDigitalTask/Controllers/GrmTaskController.cs
using GrmDigitalTask.EF;
using GrmDigitalTask.EntityModels;
using GrmDigitalTask.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GrmDigitalTask.Controllers
{
    public class GrmTaskController : Controller
    {
        private GrmTaskDbContext _context;
        public GrmTaskController(GrmTaskDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<GrmTaskPrikazVM> model = _context.GrmTask.Select(
                x => new GrmTaskPrikazVM
                {
                    ID = x.ID,
                    Name = x.Name,
                    Position = x.Position,
                    Score = x.Score
                }).OrderByDescending(x=>x.Score).ToList();

            var brojac = 0;
            List<GrmTask> grmTask = _context.GrmTask.OrderByDescending(x => x.Score).ToList();
            foreach (var item in grmTask.OrderByDescending(x => x.Score))
            {
                brojac++;
                item.Position = brojac;

                _context.SaveChanges();
            }

            return View(model);
        }
        public IActionResult Dodaj()
        {
            
            GrmTaskDodajVM model = new GrmTaskDodajVM
            {
                GrmTaskList1 = _context.GrmTask.OrderBy(x => x.Name).Select(x => new SelectListItem
                {
                    Value = x.ID.ToString(),
                    Text = x.Name
                }).ToList(),
                GrmTaskList2 = _context.GrmTask.OrderBy(x => x.Name).Select(x => new SelectListItem
                {
                    Value = x.ID.ToString(),
                    Text = x.Name
                }).ToList()
            };

            return View(model);
        }
        public IActionResult Snimi(GrmTaskDodajVM vm)
        {
            
            if(vm.ID1==vm.ID2)
            {
                ModelState.AddModelError("Drugi", "Morate odabrati razlicite iteme!");
            }
            if(vm.Prvi==vm.Drugi)
            {
                ModelState.AddModelError("Drugi", "Morate unijeti razlicite vrijednosti!");
            }
            
            
            if (!ModelState.IsValid)
            {
                vm.GrmTaskList1 = _context.GrmTask.OrderBy(x => x.Name).Select(x => new SelectListItem
                {
                    Value = x.ID.ToString(),
                    Text = x.Name
                }).ToList();
                vm.GrmTaskList2 = _context.GrmTask.OrderBy(x => x.Name).Select(x => new SelectListItem
                {
                    Value = x.ID.ToString(),
                    Text = x.Name
                }).ToList();
                   
                return View("Dodaj", vm);
            }
            if (vm.Prvi > vm.Drugi)
            {
                GrmTask grmTask = _context.GrmTask.Find(vm.ID1);
                grmTask.Score++;
            }
            else
            {
                GrmTask grmTask = _context.GrmTask.Find(vm.ID2);
                grmTask.Score++;


            }
            


            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

GrmDigitalTask/Controllers/HomeController.cs
using GrmDigitalTask.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GrmDigitalTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GrmDigitalTask/Views/GrmTask/Dodaj.cshtml
@model GrmTaskDodajVM;

<form asp-action="Snimi" method="post">
    


    <div class="form-group col-md-6">
        <label>Name</label>
        <select asp-for="ID1" asp-items="Model.GrmTaskList1" class="form-control">Odaberi</select>

        <input asp-for="Prvi" class="form-control" />
        <span asp-validation-for="Prvi" class="text-danger"></span>

    </div>

    <div class="form-group col-md-6">
        <label>Name</label>
        <select asp-for="ID2" asp-items="Model.GrmTaskList2" class="form-control">Odaberi</select>

        <input asp-for="Drugi" class="form-control" />
        <span asp-validation-for="Drugi" class="text-danger"></span>

    </div>


    <input type="submit" value="Snimi" class="btn btn-primary" />
</form>

GrmDigitalTask/Views/GrmTask/Index.cshtml
@model List<GrmTaskPrikazVM>;


<table class="table table-hover">
    <thead>
        <tr>
            <th>Position</th>
            <th>Name</th>
            <th>Score</th>

            <th class="text-right">
                <a asp-controller="GrmTask" asp-action="Dodaj" class="btn btn-info btn-sm">Dodaj score</a>
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {

        <tr>
            <td>@item.Position</td>
            <td>@item.Name</td>
            <td>@item.Score</td>

        </tr>
        }
    </tbody>
</table>

GrmDigitalTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GrmDigitalTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GrmDigitalTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GrmDigitalTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GrmDigitalTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>